title = 'Yuki Kishimoto'
theme = "hugo-coder"
baseURL = 'https://yukikishimoto.com'
languageCode = 'en-us'

[params]
  author = "Yuki Kishimoto"
  info = [
    "`🦀 Rust developer 🦀`", 
    "`Working on Bitcoin and Nostr`", 
    "`86F3 105A DFA8 AB58 7268 DCD7 8D3D CD04 2496 19D1`",
  ]
  description = "Yuki Kishimoto's personal website."
  keywords = "developer,personal"
  avatarurl = "images/avatar.jpg"
  colorScheme = "light"
  hidecolorschemetoggle = true
  disableDefaultJsScripts = true

# Social links
[[params.social]]
  name = "Github"
  #icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/yukibtc/"

[[params.social]]
  name = "PGP"
  weight = 2
  url = "PGP.asc"

[[params.social]]
  name = "Email"
  #icon = "fa fa-github fa-2x"
  weight = 3
  url = "mailto:yukikishimoto@protonmail.com"

[[params.social]]
  name = "Nostr"
  weight = 4
  url = "https://nostr.band/npub1drvpzev3syqt0kjrls50050uzf25gehpz9vgdw08hvex7e0vgfeq0eseet"

[[params.social]]
  name = "SimpleX"
  weight = 5
  url = "https://simplex.chat/contact#/?v=1-4&smp=smp%3A%2F%2F1OwYGt-yqOfe2IyVHhxz3ohqo3aCCMjtB-8wn4X_aoY%3D%40smp11.simplex.im%2FFi92VHt-Kq5GCBxQJm-VbfmspJCr-ZNP%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEA9jPaDQuDoaklq6ciXKnpH6x6RwkMvvHhefNJbaf5TH4%253D%26srv%3D6ioorbm6i3yxmuoezrhjk6f6qgkc4syabh7m3so74xunb5nzr4pwgfqd.onion"

[[params.social]]
  name = "Matrix"
  weight = 6
  url = "https://matrix.to/#/@yukikishimoto:matrix.org"
